### PR TITLE
Serverless-Act

### PR DESCRIPTION
**Pull request by 88pronet**
# Github Serverless

### CODE REVIEW

**Review by 88pronet — COMMENTED** [review]
Change

**Review by 88pronet — COMMENTED** [review]
V2

**Comment by Teakowa** [comment]
Please attention this PR will change the action name, license and readme, I recommend only merging dockerfile changes to upstream.

**Comment by dragonraid** [comment]
Hi @88pronet, thank you for contributing. However, source and forked repositories have diverged some time ago, so I cannot merge this. 

I will update serverless framework to latest version in Dockerfile by separate commit, to make it up to date.

**Review by 88pronet — COMMENTED** [review]
2.4

**Pull request closed without merging**
